package com.mbialowas.movielocator

import com.mbialowas.moviefinder.models.Character

object CharacterDataSet {

    val characterList = listOf<Character>(
        Character(
            name = "Harry Potter",
            species = "human",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "31-07-1980",
            yearOfBirth = 1980,
            ancestry = "half-blood",
            eyeColour = "green",
            hairColour = "black",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Daniel Radcliffe",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/harry.jpg"
        ),
        Character(
            name = "Hermione Granger",
            species = "human",
            gender = "female",
            house = "Gryffindor",
            dateOfBirth = "19-09-1979",
            yearOfBirth = 1979,
            ancestry = "muggleborn",
            eyeColour = "brown",
            hairColour = "brown",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Emma Watson",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/hermione.jpeg"
        ),
        Character(
            name = "Ron Weasley",
            species = "human",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "01-03-1980",
            yearOfBirth = 1980,
            ancestry = "pure-blood",
            eyeColour = "blue",
            hairColour = "red",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Rupert Grint",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/ron.jpg"
        ),
        Character(
            name = "Draco Malfoy",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "05-06-1980",
            yearOfBirth = 1980,
            ancestry = "pure-blood",
            eyeColour = "grey",
            hairColour = "blonde",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Tom Felton",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/draco.jpg"
        ),
        Character(
            name = "Minerva McGonagall",
            species = "human",
            gender = "female",
            house = "Gryffindor",
            dateOfBirth = "04-10-1925",
            yearOfBirth = 1925,
            ancestry = "",
            eyeColour = "",
            hairColour = "black",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "Dame Maggie Smith",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/mcgonagall.jpg"
        ),
        Character(
            name = "Cedric Diggory",
            species = "human",
            gender = "male",
            house = "Hufflepuff",
            dateOfBirth = "",
            yearOfBirth = 1977,
            ancestry = "",
            eyeColour = "grey",
            hairColour = "brown",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Robert Pattinson",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/cedric.png"
        ),
        Character(
            name = "Cho Chang",
            species = "human",
            gender = "female",
            house = "Ravenclaw",
            dateOfBirth = "",
            yearOfBirth = 2023,
            ancestry = "",
            eyeColour = "brown",
            hairColour = "black",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Katie Leung",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/cho.jpg"
        ),
        Character(
            name = "Severus Snape",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "09-01-1960",
            yearOfBirth = 1960,
            ancestry = "half-blood",
            eyeColour = "black",
            hairColour = "black",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "Alan Rickman",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/snape.jpg"
        ),
        Character(
            name = "Rubeus Hagrid",
            species = "half-giant",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "06-12-1928",
            yearOfBirth = 1928,
            ancestry = "half-blood",
            eyeColour = "black",
            hairColour = "black",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "Robbie Coltrane",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/hagrid.png"
        ),
        Character(
            name = "Neville Longbottom",
            species = "human",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "30-07-1980",
            yearOfBirth = 1980,
            ancestry = "pure-blood",
            eyeColour = "",
            hairColour = "blonde",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Matthew Lewis",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/neville.jpg"
        ),
        Character(
            name = "Luna Lovegood",
            species = "human",
            gender = "female",
            house = "Ravenclaw",
            dateOfBirth = "13-02-1981",
            yearOfBirth = 1981,
            ancestry = "",
            eyeColour = "grey",
            hairColour = "blonde",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Evanna Lynch",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/luna.jpg"
        ),
        Character(
            name = "Ginny Weasley",
            species = "human",
            gender = "female",
            house = "Gryffindor",
            dateOfBirth = "11-08-1981",
            yearOfBirth = 1981,
            ancestry = "pure-blood",
            eyeColour = "brown",
            hairColour = "red",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Bonnie Wright",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/ginny.jpg"
        ),
        Character(
            name = "Sirius Black",
            species = "human",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "03-11-1959",
            yearOfBirth = 1959,
            ancestry = "pure-blood",
            eyeColour = "grey",
            hairColour = "black",
            hogwartsStudent = false,
            hogwartsStaff = false,
            actor = "Gary Oldman",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/sirius.JPG"
        ),
        Character(
            name = "Remus Lupin",
            species = "werewolf",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "10-03-1960",
            yearOfBirth = 1960,
            ancestry = "half-blood",
            eyeColour = "green",
            hairColour = "brown",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "David Thewlis",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/lupin.jpg"
        ),
        Character(
            name = "Arthur Weasley",
            species = "human",
            gender = "male",
            house = "Gryffindor",
            dateOfBirth = "06-02-1950",
            yearOfBirth = 1950,
            ancestry = "pure-blood",
            eyeColour = "blue",
            hairColour = "red",
            hogwartsStudent = false,
            hogwartsStaff = false,
            actor = "Mark Williams",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/arthur.jpg"
        ),
        Character(
            name = "Bellatrix Lestrange",
            species = "human",
            gender = "female",
            house = "Slytherin",
            dateOfBirth = "",
            yearOfBirth = 1951,
            ancestry = "pure-blood",
            eyeColour = "brown",
            hairColour = "black",
            hogwartsStudent = false,
            hogwartsStaff = false,
            actor = "Helena Bonham Carter",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/bellatrix.jpg"
        ),
        Character(
            name = "Lord Voldemort",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "31-12-1926",
            yearOfBirth = 1926,
            ancestry = "half-blood",
            eyeColour = "red",
            hairColour = "bald",
            hogwartsStudent = false,
            hogwartsStaff = false,
            actor = "Ralph Fiennes",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/voldemort.jpg"
        ),
        Character(
            name = "Horace Slughorn",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "",
            yearOfBirth = 1977,
            ancestry = "pure-blood",
            eyeColour = "green",
            hairColour = "blonde",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "Jim Broadbent",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/slughorn.JPG"
        ),
        Character(
            name = "Kingsley Shacklebolt",
            species = "human",
            gender = "male",
            house = "",
            dateOfBirth = "",
            yearOfBirth = 1988,
            ancestry = "pure-blood",
            eyeColour = "brown",
            hairColour = "brown",
            hogwartsStudent = false,
            hogwartsStaff = false,
            actor = "George Harris",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/kingsley.jpg"
        ),
        Character(
            name = "Dolores Umbridge",
            species = "human",
            gender = "female",
            house = "Slytherin",
            dateOfBirth = "",
            yearOfBirth = 1983,
            ancestry = "half-blood",
            eyeColour = "brown",
            hairColour = "grey",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "Imelda Staunton",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/umbridge.jpg"
        ),
        Character(
            name = "Lucius Malfoy",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "",
            yearOfBirth = 1954,
            ancestry = "pure-blood",
            eyeColour = "grey",
            hairColour = "blonde",
            hogwartsStudent = false,
            hogwartsStaff = false,
            actor = "Jason Isaacs",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/lucius.jpg"
        ),
        Character(
            name = "Vincent Crabbe",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "",
            yearOfBirth = 1954,
            ancestry = "pure-blood",
            eyeColour = "black",
            hairColour = "black",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Jamie Waylett",
            alive = false,
            image = "http://hp-api.herokuapp.com/images/crabbe.jpg"
        ),
        Character(
            name = "Gregory Goyle",
            species = "human",
            gender = "male",
            house = "Slytherin",
            dateOfBirth = "",
            yearOfBirth = 1945,
            ancestry = "pure-blood",
            eyeColour = "",
            hairColour = "brown",
            hogwartsStudent = true,
            hogwartsStaff = false,
            actor = "Josh Herdman",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/goyle.jpg"
        ),
        Character(
            name = "Mrs Norris",
            species = "cat",
            gender = "female",
            house = "",
            dateOfBirth = "",
            yearOfBirth = 1963,
            ancestry = "",
            eyeColour = "yellow",
            hairColour = "brown",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "Maxime, Alanis and Tommy the cats",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/norris.JPG"
        ),
        Character(
            name = "Argus Filch",
            species = "human",
            gender = "male",
            house = "",
            dateOfBirth = "",
            yearOfBirth = 1999,
            ancestry = "squib",
            eyeColour = "",
            hairColour = "grey",
            hogwartsStudent = false,
            hogwartsStaff = true,
            actor = "David Bradley",
            alive = true,
            image = "http://hp-api.herokuapp.com/images/filch.jpg"
        )
        )

}